[build-system]
requires = ["setuptools>=65"]
build-backend = "setuptools.build_meta"

[project]
name = "examgen"
version = "0.1.0"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["examgen"]

